version: '3'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/powermeter
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
  db:
    image: keinos/sqlite3
    volumes:
      - db-data:/data

volumes:
  db-data: